# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
      working-directory: server

    - name: Create ENV File
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        cat .env
      working-directory: server

    - name: Build client
      run: |
        rm -rf node_modules
        npm i vite
        npm i
        npm run dev
      working-directory: client

    - run: pm2 restart api
